name: Install repository

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      with:
        run_install: false

    - name: Install node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22.13
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
